using System.Collections.Concurrent;

namespace ZDefree.Core.Watching;

public enum StrategyChangeKind { Added, Modified, Removed, Renamed }

public sealed record StrategyChangeEvent(
    StrategyChangeKind Kind,
    string FilePath,
    string? OldPath,
    DateTimeOffset At);

/// <summary>
/// Watches <c>&lt;root&gt;/common/</c> and <c>&lt;root&gt;/advanced/</c> for
/// changes to strategy JSON files, with debouncing to coalesce burst events
/// that editors (VS Code, JetBrains, etc.) emit when saving a single file.
///
/// Filters out non-strategy files automatically:
///   - <c>INDEX.json</c> (the catalog, regenerated by `zdefree index`)
///   - <c>*.schema.json</c> (JSON Schemas alongside content)
///   - any file not ending in <c>.json</c>
/// </summary>
public sealed class StrategyWatcher : IDisposable
{
    private readonly FileSystemWatcher _commonWatcher;
    private readonly FileSystemWatcher _advancedWatcher;
    private readonly TimeSpan _debounce;
    private readonly ConcurrentDictionary<string, DebouncedEntry> _pending = new(StringComparer.OrdinalIgnoreCase);
    private readonly object _emitGate = new();
    private bool _disposed;

    public event EventHandler<StrategyChangeEvent>? Changed;

    public StrategyWatcher(string strategiesRoot, TimeSpan? debounce = null)
    {
        if (string.IsNullOrEmpty(strategiesRoot))
        {
            throw new ArgumentException("strategiesRoot is required", nameof(strategiesRoot));
        }
        if (!Directory.Exists(strategiesRoot))
        {
            throw new DirectoryNotFoundException($"strategies root not found: {strategiesRoot}");
        }

        _debounce = debounce ?? TimeSpan.FromMilliseconds(250);

        _commonWatcher   = CreateWatcher(Path.Combine(strategiesRoot, "common"));
        _advancedWatcher = CreateWatcher(Path.Combine(strategiesRoot, "advanced"));
    }

    public void Start()
    {
        if (_commonWatcher.EnableRaisingEvents == false)   _commonWatcher.EnableRaisingEvents   = true;
        if (_advancedWatcher.EnableRaisingEvents == false) _advancedWatcher.EnableRaisingEvents = true;
    }

    public void Stop()
    {
        _commonWatcher.EnableRaisingEvents   = false;
        _advancedWatcher.EnableRaisingEvents = false;
    }

    private FileSystemWatcher CreateWatcher(string path)
    {
        // Auto-create the subdir if it doesn't exist — keeps the watcher usable
        // even on a fresh distro where only one of common/advanced is populated.
        Directory.CreateDirectory(path);

        var w = new FileSystemWatcher(path, "*.json")
        {
            IncludeSubdirectories = false,
            NotifyFilter = NotifyFilters.FileName | NotifyFilters.LastWrite | NotifyFilters.Size,
        };

        w.Created  += (_, e) => Enqueue(StrategyChangeKind.Added,    e.FullPath);
        w.Changed  += (_, e) => Enqueue(StrategyChangeKind.Modified, e.FullPath);
        w.Deleted  += (_, e) => Enqueue(StrategyChangeKind.Removed,  e.FullPath);
        w.Renamed  += (_, e) => Enqueue(StrategyChangeKind.Renamed,  e.FullPath, oldPath: e.OldFullPath);
        // Silently drop watcher errors — they're usually transient (file lock,
        // user moving dir). Real failures will resurface on next event.
        w.Error    += (_, _) => { };

        return w;
    }

    private void Enqueue(StrategyChangeKind kind, string fullPath, string? oldPath = null)
    {
        if (!ShouldEmit(fullPath)) return;

        string key = fullPath.ToLowerInvariant();
        DateTimeOffset deadline = DateTimeOffset.UtcNow + _debounce;

        // Precedence when merging events for the same file in the debounce window:
        //   Removed > Added > Renamed > Modified.
        // FSW on Windows often fires Created+Changed for a single File.WriteAllText
        // call; without this, the Added would collapse into Modified.
        _pending.AddOrUpdate(
            key,
            _ => new DebouncedEntry(kind, fullPath, oldPath, deadline),
            (_, existing) =>
            {
                var winning = MergeKind(existing.Kind, kind);
                return new DebouncedEntry(winning, fullPath, oldPath ?? existing.OldPath, deadline);
            });

        _ = Task.Delay(_debounce).ContinueWith(_ => DispatchIfDue(key));
    }

    private static StrategyChangeKind MergeKind(StrategyChangeKind existing, StrategyChangeKind incoming)
    {
        if (existing == StrategyChangeKind.Removed || incoming == StrategyChangeKind.Removed)
            return StrategyChangeKind.Removed;
        if (existing == StrategyChangeKind.Added   || incoming == StrategyChangeKind.Added)
            return StrategyChangeKind.Added;
        if (existing == StrategyChangeKind.Renamed || incoming == StrategyChangeKind.Renamed)
            return StrategyChangeKind.Renamed;
        return StrategyChangeKind.Modified;
    }

    private void DispatchIfDue(string key)
    {
        if (!_pending.TryGetValue(key, out var entry)) return;
        if (DateTimeOffset.UtcNow < entry.Deadline) return;
        if (!_pending.TryRemove(key, out var final)) return;

        StrategyChangeEvent ev;
        lock (_emitGate)
        {
            ev = new StrategyChangeEvent(final.Kind, final.FullPath, final.OldPath, DateTimeOffset.UtcNow);
        }

        try { Changed?.Invoke(this, ev); }
        catch { /* subscriber threw — swallow to keep watcher alive */ }
    }

    /// <summary>
    /// Visible for testability — same filter rules as the live watcher.
    /// </summary>
    public static bool ShouldEmit(string fullPath)
    {
        string name = Path.GetFileName(fullPath);
        if (!name.EndsWith(".json", StringComparison.OrdinalIgnoreCase)) return false;
        if (name.Equals("INDEX.json", StringComparison.OrdinalIgnoreCase)) return false;
        if (name.EndsWith(".schema.json", StringComparison.OrdinalIgnoreCase)) return false;
        return true;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        Stop();
        _commonWatcher.Dispose();
        _advancedWatcher.Dispose();
    }

    private sealed record DebouncedEntry(
        StrategyChangeKind Kind,
        string FullPath,
        string? OldPath,
        DateTimeOffset Deadline);
}
